language: python
python:

  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
install:
  - pip install coverage
# command to run tests
script:
  - python -m unittest tests.py truthTables.py

#install sentry
script:
  - pip install


# Run the unit test
script:
  - coverage run tests.py

# Push the results back to codecov
after_success:
  - codecov
