language: python
python:

  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
install:
  - pip install coverage
#install sentry
script:
  - pip install sentry-sdk
# command to run tests
script:
  - python -m unittest tests.py truthTables.py



# Push the results back to codecov
after_success:
  - codecov
